name: test-pr-actions
on: [push]
permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.6"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
    - name: Install dependencies
      run: |
        python3.10 -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py develop
    - name: Test with pytest
      run: |
        pytest tests
